
<!-- Generated by ai2html on 2022-02-22 20:02 -->
<!-- ai file: ai2html.ai -->

<script>
	import { onMount } from 'svelte';
	onMount(() => {
		(function (containerId, opts) {
			if (!('querySelector' in document)) return;
			var container = document.getElementById(containerId);
			var nameSpace = opts.namespace || '';
			var onResize = throttle(update, 200);
			var waiting = !!window.IntersectionObserver;
			var observer;
			update();

			document.addEventListener('DOMContentLoaded', update);
			window.addEventListener('resize', onResize);

			function update() {
				var artboards = selectChildren('.' + nameSpace + 'artboard[data-min-width]', container),
					width = Math.round(container.getBoundingClientRect().width);

				// Set artboard visibility based on container width
				artboards.forEach(function (el) {
					var minwidth = el.getAttribute('data-min-width'),
						maxwidth = el.getAttribute('data-max-width');
					if (+minwidth <= width && (+maxwidth >= width || maxwidth === null)) {
						if (!waiting) {
							selectChildren('.' + nameSpace + 'aiImg', el).forEach(updateImgSrc);
						}
						el.style.display = 'block';
					} else {
						el.style.display = 'none';
					}
				});

				// Initialize lazy loading on first call
				if (waiting && !observer) {
					if (elementInView(container)) {
						waiting = false;
						update();
					} else {
						observer = new IntersectionObserver(onIntersectionChange, {});
						observer.observe(container);
					}
				}
			}

			function elementInView(el) {
				var bounds = el.getBoundingClientRect();
				return bounds.top < window.innerHeight && bounds.bottom > 0;
			}

			// Replace blank placeholder image with actual image
			function updateImgSrc(img) {
				var src = img.getAttribute('data-src');
				if (src && img.getAttribute('src') != src) {
					img.setAttribute('src', src);
				}
			}

			function onIntersectionChange(entries) {
				// There may be multiple entries relating to the same container
				// (captured at different times)
				var isIntersecting = entries.reduce(function (memo, entry) {
					return memo || entry.isIntersecting;
				}, false);
				if (isIntersecting) {
					waiting = false;
					// update: don't remove -- we need the observer to trigger an update
					// when a hidden map becomes visible after user interaction
					// (e.g. when an accordion menu or tab opens)
					// observer.disconnect();
					// observer = null;
					update();
				}
			}

			function selectChildren(selector, parent) {
				return parent ? Array.prototype.slice.call(parent.querySelectorAll(selector)) : [];
			}

			// based on underscore.js
			function throttle(func, wait) {
				var timeout = null,
					previous = 0;
				function run() {
					previous = Date.now();
					timeout = null;
					func();
				}
				return function () {
					var remaining = wait - (Date.now() - previous);
					if (remaining <= 0 || remaining > wait) {
						clearTimeout(timeout);
						run();
					} else if (!timeout) {
						timeout = setTimeout(run, remaining);
					}
				};
			}
		})("g-ai2html-box", {namespace: "g-", setup: window.setupInteractive || window.getComponent});
		});
</script>

<div id="g-ai2html-box" class="ai2html">
	<!-- Artboard: 900px -->
	<div id="g-900px" class="g-artboard" style="min-width: 900px;" data-aspect-ratio="1.576" data-min-width="900">
<div style="padding: 0 0 63.4444% 0;"></div>
		<img id="g-900px-img" class="g-aiImg" alt="A description of the artboards." src="images/ai2html/900px.png?v=1"/>
		<div id="g-ai0-1" class="g-art g-aiAbs g-aiPointText" style="bottom:41.2289%;left:49.9782%;margin-left:-109px;width:218px;">
			<p class="g-pstyle0">900px</p>
		</div>
	</div>

	<!-- Artboard: 640px -->
	<div id="g-640px" class="g-artboard" style="min-width: 640px;max-width: 899px;max-height: 506px" data-aspect-ratio="1.778" data-min-width="640" data-max-width="899">
<div style="padding: 0 0 56.25% 0;"></div>
		<img id="g-640px-img" class="g-aiImg" alt="A description of the artboards." src="images/ai2html/640px.png?v=1"/>
		<div id="g-ai1-1" class="g-art g-aiAbs g-aiPointText" style="bottom:33.3103%;left:50.0126%;margin-left:-109px;width:218px;">
			<p class="g-pstyle0">640px</p>
		</div>
	</div>

	<!-- Artboard: 555px -->
	<div id="g-555px" class="g-artboard" style="min-width: 555px;max-width: 639px;max-height: 414px" data-aspect-ratio="1.542" data-min-width="555" data-max-width="639">
<div style="padding: 0 0 64.8649% 0;"></div>
		<img id="g-555px-img" class="g-aiImg" alt="A description of the artboards." src="images/ai2html/555px.png?v=1"/>
		<div id="g-ai2-1" class="g-art g-aiAbs g-aiPointText" style="bottom:33.4492%;left:50.0446%;margin-left:-109px;width:218px;">
			<p class="g-pstyle0">555px</p>
		</div>
	</div>

	<!-- Artboard: 300px -->
	<div id="g-300px" class="g-artboard" style="max-width: 554px;max-height: 666px" data-aspect-ratio="0.832" data-min-width="0" data-max-width="554">
<div style="padding: 0 0 120.1667% 0;"></div>
		<img id="g-300px-img" class="g-aiImg" alt="A description of the artboards." src="images/ai2html/300px.png?v=1"/>
		<div id="g-ai3-1" class="g-art g-aiAbs" style="top:36.061%;left:49.9714%;margin-left:-32.6667%;width:65.3333%;">
			<p class="g-pstyle0">300px</p>
		</div>
	</div>
</div><style>
	#g-ai2html-box ,
	#g-ai2html-box .g-artboard {
		margin:0 auto;
	}
	#g-ai2html-box p {
		margin:0;
	}
	#g-ai2html-box .g-aiAbs {
		position:absolute;
	}
	#g-ai2html-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
	}
	#g-ai2html-box .g-aiSymbol {
		position: absolute;
		box-sizing: border-box;
	}
	#g-ai2html-box .g-aiPointText p { white-space: nowrap; }
	#g-900px {
		position:relative;
		overflow:hidden;
	}
	#g-900px p {
		font-family:arial,helvetica,sans-serif;
		line-height:86px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:72px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-900px .g-pstyle0 {
		height:86px;
		text-align:center;
	}
	#g-640px {
		position:relative;
		overflow:hidden;
	}
	#g-640px p {
		font-family:arial,helvetica,sans-serif;
		line-height:86px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:72px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-640px .g-pstyle0 {
		height:86px;
		text-align:center;
	}
	#g-555px {
		position:relative;
		overflow:hidden;
	}
	#g-555px p {
		font-family:arial,helvetica,sans-serif;
		line-height:86px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:72px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-555px .g-pstyle0 {
		height:86px;
		text-align:center;
	}
	#g-300px {
		position:relative;
		overflow:hidden;
	}
	#g-300px p {
		font-family:arial,helvetica,sans-serif;
		line-height:86px;
		opacity:1;
		letter-spacing:0em;
		font-size:72px;
		text-align:left;
		color:rgb(255,255,255);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		height:auto;
		position:static;
	}
	#g-300px .g-pstyle0 {
		text-align:center;
	}

</style>
<!-- End ai2html - 2022-02-22 20:02 -->
